### ISSUE TITLE
Swapper docs have wrong illustration

### ISSUE THREAD

**Issue by AhmadDecoded** [0xSplits/docs#16]
On the following page:
https://dev.docs.0xsplits.xyz/core/swapper
First image illustration is wrong IMO, caller sends no tokens to swapper when calling the flash function while in docs it shows that the caller is sending the DAI, caller only receive the reward Eth or erc20 for calling the flash function.
This needs correction as protocol is going through audit and may lead to misconception.

**Comment by abramdawson** [comment]
Thanks @AhmadDecoded - we've updated the image to be more accurate
