### ISSUE TITLE
Is "useWithdrawWarehouse" missing from the react docs?

### ISSUE THREAD

**Issue by atjeff** [0xSplits/docs#54]
Hey guys, 

Trying to understand the new "V2" flow. 

From what I understand, a "pull" (which is default) V2 Splits will allow a user to claim funds from the warehouse, AFTER distribute has been called on the splits contract?

I do see in the docs for the V1 Splits there is a withdraw method, but I don't think that's what I need for V2. 

Is "useWithdrawWarehouse" (seen in the React SDK code itself) what we need to be using instead?

Best,
Jeff

**Comment by r0ohafza** [comment]
Hey @atjeff, thank you for pointing this out, the two hooks were missing in the docs. I just updated the docs with them. I think the [`useWithdrawWarehouse`](https://docs.splits.org/react#usewithdrawwarehouse) hook is what you would need here.

**Comment by atjeff** [comment]
Thank you!
